git clone git@github.com:fwsGonzo/IncludeOS.git
git clone git@github.com:fwsGonzo/websockets.git
git clone git@github.com:tickless/vmrunner.git
git clone git@github.com:tickless/conan.git
git clone git@github.com:includeos/conan_config.git
git clone git@github.com:includeos/diskbuilder.git
git clone git@github.com:includeos/solo5.git
git clone git@github.com:includeos/vmbuild.git
git clone git@github.com:fwsGonzo/musl.git
git clone git@github.com:tickless/demo-examples.git
git clone git@github.com:tickless/microlb.git
